PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE packages (     id           INTEGER PRIMARY KEY AUTOINCREMENT,     name         TEXT NOT NULL UNIQUE,     version      TEXT NOT NULL,     description  TEXT,     category     TEXT,     author       TEXT,     license      TEXT,     layer        TEXT DEFAULT 'both',     created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,     updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE files (     id           INTEGER PRIMARY KEY AUTOINCREMENT,     package_id   INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,     filename     TEXT NOT NULL,     filepath     TEXT NOT NULL,     filetype     TEXT,     checksum     TEXT,     size_bytes   INTEGER,     content      BLOB,     layer        TEXT DEFAULT 'both' );
CREATE TABLE dependencies (     id               INTEGER PRIMARY KEY AUTOINCREMENT,     package_id       INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,     depends_on_name  TEXT NOT NULL,     min_version      TEXT,     max_version      TEXT,     layer            TEXT DEFAULT 'both' );
CREATE TABLE installed (     id            INTEGER PRIMARY KEY AUTOINCREMENT,     package_id    INTEGER NOT NULL REFERENCES packages(id),     installed_at  DATETIME DEFAULT CURRENT_TIMESTAMP,     install_path  TEXT NOT NULL,     installed_by  TEXT,     layer         TEXT );
CREATE TABLE history (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     action      TEXT NOT NULL,     package_id  INTEGER REFERENCES packages(id),     target_dir  TEXT,     timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP,     status      TEXT,     layer       TEXT,     notes       TEXT );
CREATE TABLE toc (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     title       TEXT NOT NULL,     parent_id   INTEGER REFERENCES toc(id),     position    INTEGER,     description TEXT,     layer       TEXT DEFAULT 'both' );
CREATE TABLE toc_entries (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     toc_id      INTEGER NOT NULL REFERENCES toc(id) ON DELETE CASCADE,     package_id  INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,     position    INTEGER );
CREATE TABLE glossary (     id                 INTEGER PRIMARY KEY AUTOINCREMENT,     term               TEXT NOT NULL UNIQUE,     definition         TEXT NOT NULL,     example            TEXT,     related_package_id INTEGER REFERENCES packages(id),     category           TEXT,     layer              TEXT DEFAULT 'both' );
CREATE TABLE aliases (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     alias       TEXT NOT NULL UNIQUE,     target_type TEXT NOT NULL,     target_id   INTEGER,     target_name TEXT,     layer       TEXT DEFAULT 'both',     created_at  DATETIME DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE kernel_slots (     id         INTEGER PRIMARY KEY AUTOINCREMENT,     slot       INTEGER UNIQUE NOT NULL,     kernel_id  INTEGER REFERENCES packages(id),     status     TEXT,     kernel_type TEXT,     loaded_at  DATETIME,     checksum   TEXT,     layer      TEXT DEFAULT 'both',     notes      TEXT );
INSERT INTO "kernel_slots" ("id","slot","kernel_id","status","kernel_type","loaded_at","checksum","layer","notes") VALUES(1,0,NULL,'empty','c_pure',NULL,NULL,'both','Pure C - maximum speed, peak traffic');
INSERT INTO "kernel_slots" ("id","slot","kernel_id","status","kernel_type","loaded_at","checksum","layer","notes") VALUES(2,1,NULL,'empty','c_sideload',NULL,NULL,'both','C + sideload - balanced, extended calls');
INSERT INTO "kernel_slots" ("id","slot","kernel_id","status","kernel_type","loaded_at","checksum","layer","notes") VALUES(3,2,NULL,'empty','python_user',NULL,NULL,'both','Python userspace - flexible, moderate load');
INSERT INTO "kernel_slots" ("id","slot","kernel_id","status","kernel_type","loaded_at","checksum","layer","notes") VALUES(4,3,NULL,'empty','python_full',NULL,NULL,'both','Python 100 - full flexibility, dev/low priority');
CREATE TABLE sideloads (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     slot        INTEGER NOT NULL REFERENCES kernel_slots(slot),     package_id  INTEGER NOT NULL REFERENCES packages(id),     priority    INTEGER,     status      TEXT,     layer       TEXT DEFAULT 'both' );
CREATE TABLE rotation_log (     id            INTEGER PRIMARY KEY AUTOINCREMENT,     from_slot     INTEGER,     to_slot       INTEGER,     trigger       TEXT,     traffic_load  REAL,     layer         TEXT,     timestamp     DATETIME DEFAULT CURRENT_TIMESTAMP,     success       INTEGER );
CREATE TABLE subscribers (     id              INTEGER PRIMARY KEY AUTOINCREMENT,     name            TEXT NOT NULL,     service         TEXT NOT NULL,     tunnel_in       TEXT,     tunnel_out      TEXT,     status          TEXT,     provisioned_at  DATETIME,     last_fed        DATETIME,     layer           TEXT DEFAULT 'both' );
CREATE TABLE feed_log (     id            INTEGER PRIMARY KEY AUTOINCREMENT,     subscriber_id INTEGER NOT NULL REFERENCES subscribers(id),     package_id    INTEGER REFERENCES packages(id),     action        TEXT,     status        TEXT,     bytes_moved   INTEGER,     timestamp     DATETIME DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE layer_assignments (     id           INTEGER PRIMARY KEY AUTOINCREMENT,     service      TEXT NOT NULL,     layer        TEXT NOT NULL,     native_call  TEXT,     can_migrate  INTEGER DEFAULT 1,     reason       TEXT );
CREATE TABLE system_telemetry (     id            INTEGER PRIMARY KEY AUTOINCREMENT,     metric        TEXT NOT NULL,     value         REAL NOT NULL,     layer         TEXT,     slot          INTEGER,     subscriber_id INTEGER REFERENCES subscribers(id),     timestamp     DATETIME DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE system_snapshots (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     label       TEXT NOT NULL,     layer       TEXT,     state       TEXT,     checksum    TEXT,     is_good     INTEGER DEFAULT 1,     created_at  DATETIME DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE entry_points (     id          INTEGER PRIMARY KEY AUTOINCREMENT,     name        TEXT UNIQUE NOT NULL,     status      TEXT DEFAULT 'reserved',     module      TEXT,     layer       TEXT DEFAULT 'both',     config      TEXT,     notes       TEXT );
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(1,'prefetch','reserved',NULL,'both',NULL,'Prefetch prediction engine hook');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(2,'healing','reserved',NULL,'both',NULL,'Self-healing trigger hook');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(3,'tunnel_in','reserved',NULL,'both',NULL,'Ingress tunnel handler');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(4,'tunnel_out','reserved',NULL,'both',NULL,'Egress tunnel handler');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(5,'sync_linux','reserved',NULL,'both',NULL,'Linux global sync via zsh');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(6,'sync_windows','reserved',NULL,'both',NULL,'Windows global sync via PowerShell/BITS');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(7,'kernel_rotate','reserved',NULL,'both',NULL,'Revolver rotation trigger');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(8,'game_engine','reserved',NULL,'both',NULL,'Sacrifice game engine hook');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(9,'office_engine','reserved',NULL,'both',NULL,'Phoenix Office suite hook');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(10,'db_hat','reserved',NULL,'both',NULL,'Phoenix DB/HAT form engine hook');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(11,'clone','reserved',NULL,'both',NULL,'System clone from snapshot');
INSERT INTO "entry_points" ("id","name","status","module","layer","config","notes") VALUES(12,'bridge','reserved',NULL,'both',NULL,'Windows/Linux bridge coordinator');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('entry_points',12);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('kernel_slots',4);
CREATE INDEX idx_packages_name      ON packages(name);
CREATE INDEX idx_packages_category  ON packages(category);
CREATE INDEX idx_packages_layer     ON packages(layer);
CREATE INDEX idx_files_package      ON files(package_id);
CREATE INDEX idx_files_filename     ON files(filename);
CREATE INDEX idx_files_layer        ON files(layer);
CREATE INDEX idx_deps_package       ON dependencies(package_id);
CREATE INDEX idx_deps_name          ON dependencies(depends_on_name);
CREATE INDEX idx_toc_parent         ON toc(parent_id);
CREATE INDEX idx_toc_position       ON toc(position);
CREATE INDEX idx_toc_entries_toc    ON toc_entries(toc_id);
CREATE INDEX idx_toc_entries_pkg    ON toc_entries(package_id);
CREATE INDEX idx_glossary_term      ON glossary(term);
CREATE INDEX idx_glossary_category  ON glossary(category);
CREATE INDEX idx_aliases_alias      ON aliases(alias);
CREATE INDEX idx_aliases_type       ON aliases(target_type);
CREATE INDEX idx_kernel_status      ON kernel_slots(status);
CREATE INDEX idx_kernel_slot        ON kernel_slots(slot);
CREATE INDEX idx_sideloads_slot     ON sideloads(slot);
CREATE INDEX idx_telemetry_time     ON system_telemetry(timestamp);
CREATE INDEX idx_telemetry_metric   ON system_telemetry(metric);
CREATE INDEX idx_telemetry_layer    ON system_telemetry(layer);
CREATE INDEX idx_subscribers_status ON subscribers(status);
CREATE INDEX idx_subscribers_service ON subscribers(service);
CREATE INDEX idx_feed_subscriber    ON feed_log(subscriber_id);
CREATE INDEX idx_feed_time          ON feed_log(timestamp);
CREATE INDEX idx_snapshots_good     ON system_snapshots(is_good);
CREATE INDEX idx_snapshots_layer    ON system_snapshots(layer);
CREATE INDEX idx_history_action     ON history(action);
CREATE INDEX idx_history_time       ON history(timestamp);
CREATE INDEX idx_rotation_time      ON rotation_log(timestamp);
CREATE VIEW view_toc_tree AS SELECT     t1.id       AS chapter_id,     t1.title    AS chapter,     t2.id       AS section_id,     t2.title    AS section,     t1.position AS chapter_order,     t2.position AS section_order FROM toc t1 LEFT JOIN toc t2 ON t2.parent_id = t1.id WHERE t1.parent_id IS NULL ORDER BY t1.position, t2.position;
CREATE VIEW view_active_kernel AS SELECT     ks.slot,     ks.kernel_type,     p.name      AS kernel_name,     p.version,     ks.loaded_at,     ks.layer FROM kernel_slots ks LEFT JOIN packages p ON ks.kernel_id = p.id WHERE ks.status = 'active';
CREATE VIEW view_subscriber_health AS SELECT     s.name,     s.service,     s.status,     s.last_fed,     ROUND((JULIANDAY('now') - JULIANDAY(s.last_fed)) * 24, 2) AS hours_since_fed FROM subscribers s ORDER BY hours_since_fed DESC;
CREATE VIEW view_installed AS SELECT     p.name,     p.version,     p.category,     i.install_path,     i.layer,     i.installed_at FROM installed i JOIN packages p ON i.package_id = p.id ORDER BY i.installed_at DESC;
